name: make lint
on: push

jobs:
  build:
    my-jobs:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        # make depends on poetry
        - name: install dependecies
          run: |
            pip install poetry
            make install
        - name: run lint
          run: |
            make lint
